GET http://localhost:3000/users

###
PUT http://localhost:3000/users/id
Content-Type: application/json

{
    "id":100,
    "name":"jkg",
    "age":24
}

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "id":100,
    "name":"tk",
    "age":19
}

### read a user by id
GET http://localhost:3000/users/100


### 
DELETE http://localhost:3000/users/100


### product testing 

GET http://localhost:3000/products


###
GET http://localhost:3000/products-id/100

###
GET http://localhost:3000/products-brand/nike

### 

POST http://localhost:3000/products
Content-Type: application/json

{
    "productId":100,
    "name":"shoe",
    "price":1000,
    "brand":"nike"
}

###
PUT http://localhost:3000/products/100
Content-Type: application/json

{
    "productId":100,
    "name":"shoes",
    "price":1000,
    "brand":"nike"
}

### 
DELETE http://localhost:3000/products/100